CREATE TABLE IF NOT EXISTS Users(
id TEXT NOT NULL UNIQUE,
publickey TEXT NOT NULL,
created TIMESTAMPTZ NOT NULL,
PRIMARY KEY(id)
);

CREATE TABLE IF NOT EXISTS Devices(
id TEXT NOT NULL UNIQUE,
userId TEXT NOT NULL,
created TIMESTAMPTZ NOT NULL,
PRIMARY KEY(id),
CONSTRAINT ud_fk FOREIGN KEY(userId) REFERENCES Users(id)
);

CREATE TABLE IF NOT EXISTS Credentials(
id TEXT NOT NULL UNIQUE,
service VARCHAR(16) NOT NULL,
fields TEXT NOT NULL,
userId TEXT NOT NULL,
created TIMESTAMPTZ NOT NULL,
updated TIMESTAMPTZ NOT NULL,
PRIMARY KEY(id),
CONSTRAINT uc_fk FOREIGN KEY(userId) REFERENCES Users(id)
);
