CREATE TABLE IF NOT EXISTS credentials(
id TEXT NOT NULL UNIQUE,
service VARCHAR(16) NOT NULL,
fields TEXT NOT NULL,
userId TEXT NOT NULL,
created TIMESTAMP NOT NULL,
updated TIMESTAMP NOT NULL,
PRIMARY KEY(id),
CONSTRAINT uc_fk FOREIGN KEY(userId) REFERENCES Users(id)
);
